Repository Ambiplatforms-TORQUE/ethermint, pull requests merged in 2022-08, with the labels that each got.

#42 update(feat): change default maxGasWanted
  app/ante/eth.go
  app/ante/eth_test.go
  server/config/config.go
Labels: go

#43 ENG 119 json rpc unit tests
  go.mod
  go.sum
  proto/ethermint/crypto/v1/ethsecp256k1/keys.proto
  proto/ethermint/evm/v1/evm.proto
  proto/ethermint/evm/v1/genesis.proto
  proto/ethermint/evm/v1/query.proto
  proto/ethermint/evm/v1/tx.proto
  proto/ethermint/feemarket/v1/feemarket.proto
  proto/ethermint/feemarket/v1/genesis.proto
  proto/ethermint/feemarket/v1/query.proto
  proto/ethermint/types/v1/account.proto
  proto/ethermint/types/v1/web3.proto
  rpc/backend/backend.go
  rpc/backend/backend_suite_test.go
  rpc/backend/client_test.go
  rpc/backend/evm_backend.go
  rpc/backend/evm_backend_test.go
  rpc/backend/mocks/client.go
  rpc/backend/query_client_test.go
  rpc/backend/utils.go
  rpc/namespaces/ethereum/eth/api.go
  rpc/types/utils.go
  x/evm/keeper/grpc_query.go
  x/evm/types/evm.pb.go
Labels: bug, enhancement, go

#48 feat(ante, evm): set priority for eth transactions
  app/ante/eth.go
  app/ante/eth_test.go
  app/ante/handler_options.go
  app/ante/interfaces.go
  default.nix
  go.mod
  go.sum
  gomod2nix.toml
  rpc/namespaces/ethereum/eth/api.go
  tests/integration_tests/configs/default.jsonnet
  tests/integration_tests/network.py
  tests/integration_tests/test_priority.py
  tests/integration_tests/utils.py
  x/evm/handler_test.go
  x/evm/keeper/integration_test.go
  x/evm/keeper/keeper.go
  x/evm/keeper/utils.go
  x/evm/keeper/utils_test.go
  x/evm/types/access_list_tx.go
  x/evm/types/dynamic_fee_tx.go
  x/evm/types/legacy_tx.go
  x/evm/types/tx_data.go
  x/feemarket/keeper/integration_test.go
Labels: bug, enhancement

#52 feat: support dynamic app db backend flag
  Makefile
  cmd/ethermintd/root.go
  server/flags/flags.go
  server/start.go
Labels: enhancement
