Repository Ambiplatforms-TORQUE/ethermint, pull requests merged in 2022-07, with the labels that each got.

#14 fix: traceTransaction returns zero gas used
  x/evm/keeper/grpc_query_test.go
  x/evm/keeper/state_transition.go
Labels: bug, go

#16 bug(fix): Fix go formatting issue
  app/app.go
  x/evm/keeper/grpc_query_test.go
  x/evm/keeper/state_transition.go
Labels: bug, go

#17 fix(rpc): fix panic on breaking EVM and feemarket params
  .mergify.yml
  server/json_rpc.go
  x/evm/keeper/params.go
  x/feemarket/keeper/params.go
Labels: bug, documentation, go

#20 impr(evm): add check msg.Validate check to prevent 0 gas txs
  client/docs/statik/statik.go
  client/docs/swagger-ui/swagger.yaml
  x/evm/keeper/benchmark_test.go
  x/evm/keeper/integration_test.go
  x/evm/keeper/keeper_test.go
  x/evm/keeper/state_transition_benchmark_test.go
  x/evm/keeper/statedb_benchmark_test.go
  x/evm/types/errors.go
  x/evm/types/msg.go
  x/evm/types/msg_test.go
  x/feemarket/keeper/integration_test.go
Labels: bug, go, C:CLI
